"use client";
import { useEffect, useState } from "react";
import { db } from "../../lib/firebase";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc } from "firebase/firestore";

export default function Admin(){
 const [logged,setLogged]=useState(false); const [pass,setPass]=useState(""); const [qs,setQs]=useState([]); const [students,setStudents]=useState([]); const [status,setStatus]=useState({active:false,duration:300});
 const [q,setQ]=useState({question:"",optionA:"",optionB:"",optionC:"",optionD:"",answer:"A"}); const [editing,setEditing]=useState(null); const [msg,setMsg]=useState("");
 useEffect(()=>{setLogged(localStorage.getItem("hitsAdmin")==="yes")},[]);
 useEffect(()=>onSnapshot(query(collection(db,"questions")),s=>setQs(s.docs.map(d=>({id:d.id,...d.data()})))),[]);
 useEffect(()=>onSnapshot(query(collection(db,"students"),orderBy("score","desc")),s=>setStudents(s.docs.map(d=>({id:d.id,...d.data()})))),[]);
 useEffect(()=>onSnapshot(doc(db,"settings","quiz"),s=>setStatus(s.exists()?s.data():{active:false,duration:300})),[]);
 function login(){ if(pass===(process.env.NEXT_PUBLIC_ADMIN_PASSWORD||"hits2026")){localStorage.setItem("hitsAdmin","yes");setLogged(true)} else setMsg("Wrong password"); }
 async function saveQ(){ if(!q.question||!q.optionA||!q.optionB||!q.optionC||!q.optionD){setMsg("Fill all question fields");return;} if(editing){await updateDoc(doc(db,"questions",editing),q);setEditing(null)}else{await addDoc(collection(db,"questions"),{...q,createdAt:serverTimestamp()})} setQ({question:"",optionA:"",optionB:"",optionC:"",optionD:"",answer:"A"}); setMsg("Question saved"); }
 function edit(x){setEditing(x.id);setQ({question:x.question,optionA:x.optionA,optionB:x.optionB,optionC:x.optionC,optionD:x.optionD,answer:x.answer||"A"})}
 async function launch(){await setDoc(doc(db,"settings","quiz"),{active:true,duration:Number(status.duration||300),startTime:serverTimestamp()},{merge:true});}
 async function stop(){await setDoc(doc(db,"settings","quiz"),{active:false},{merge:true});}
 if(!logged)return <><Header/><main className="main"><section className="card" style={{maxWidth:460,margin:"auto"}}><h2>Admin Login</h2><input className="input" type="password" placeholder="Admin Password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')login()}}/><button className="btn" onClick={login}>Login</button>{msg&&<div className="notice">{msg}</div>}</section></main></>;
 return <><Header/><main className="main"><div className="grid"><section className="card"><div className="nav"><h2>Admin Dashboard</h2><button className="btn2" onClick={()=>{localStorage.removeItem("hitsAdmin");location.reload()}}>Logout</button></div><div className="notice success">Status: {status.active?"Quiz LIVE":"Quiz STOPPED"}</div><div className="row"><input className="input" type="number" placeholder="Duration seconds" value={status.duration||300} onChange={e=>setStatus({...status,duration:e.target.value})}/><div><button className="btn green" onClick={launch}>Launch Quiz</button> <button className="btn danger" onClick={stop}>Stop</button></div></div><h3>{editing?"Edit Question":"Add Question"}</h3><textarea className="textarea" placeholder="Question" value={q.question} onChange={e=>setQ({...q,question:e.target.value})}/><div className="row"><input className="input" placeholder="Option A" value={q.optionA} onChange={e=>setQ({...q,optionA:e.target.value})}/><input className="input" placeholder="Option B" value={q.optionB} onChange={e=>setQ({...q,optionB:e.target.value})}/><input className="input" placeholder="Option C" value={q.optionC} onChange={e=>setQ({...q,optionC:e.target.value})}/><input className="input" placeholder="Option D" value={q.optionD} onChange={e=>setQ({...q,optionD:e.target.value})}/></div><select className="select" value={q.answer} onChange={e=>setQ({...q,answer:e.target.value})}>{["A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select><button className="btn" onClick={saveQ}>{editing?"Update":"Add Question"}</button>{editing&&<button className="btn2" onClick={()=>{setEditing(null);setQ({question:"",optionA:"",optionB:"",optionC:"",optionD:"",answer:"A"})}}>Cancel</button>}{msg&&<div className="notice">{msg}</div>}<h3>Questions ({qs.length})</h3>{qs.map((x,i)=><div className="q" key={x.id}><b>{i+1}. {x.question}</b><p className="muted">Answer: {x.answer}</p><button className="smallbtn" onClick={()=>edit(x)}>Edit</button> <button className="smallbtn" onClick={()=>deleteDoc(doc(db,"questions",x.id))}>Delete</button></div>)}</section><Leaderboard data={students}/></div></main></>;
}
function Header(){return <header className="top"><div className="wrap nav"><div><div className="brand">HITS Quiz Portal</div><div className="sub">Admin Control Panel</div></div><a className="btn2" href="/">Student Page</a></div></header>}
function Leaderboard({data}){return <aside className="card"><h3>Live Leaderboard</h3><table className="leader"><thead><tr><th>Rank</th><th>Name</th><th>Dept</th><th>Score</th></tr></thead><tbody>{data.map((s,i)=><tr key={s.id}><td>{i+1}</td><td>{s.name}</td><td>{s.dept}</td><td>{s.score||0}</td></tr>)}</tbody></table></aside>}
